version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: escaner_total_app
    restart: unless-stopped
    ports:
      - "8181:80"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8181

      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: escaner_total
      DB_USERNAME: escaner_user
      DB_PASSWORD: root

      # Opcionales para demo (puedes cambiarlos a false)
      RUN_MIGRATIONS: "true"
      RUN_SEEDERS: "true"
      SEEDER_CLASS: Database\Seeders\DatabaseSeeder
    volumes:
      - storage_data:/var/www/html/storage
    depends_on:
      - db
    networks:
      - escaner_net

  db:
    image: mysql:8.0
    container_name: escaner_total_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: escaner_total
      MYSQL_USER: escaner_user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - escaner_net

networks:
  escaner_net:
    driver: bridge

volumes:
  db_data:
  storage_data:


